### ISSUE TITLE
老哥造福世界

### ISSUE THREAD

**Issue by Hoantrbl** [Ftine/SZU_Latex_Master_Template#1]

**Comment by Hoantrbl** [comment]
引用没办法上角标

<img width="164" alt="image" src="https://github.com/Ftine/SZU_Latex_Master_Template/assets/48271804/b99b4a5a-afb0-4357-ac05-7700b7aed759">

**Comment by miRemid** [comment]
使用`\upcite`

https://github.com/Ftine/SZU_Latex_Master_Template/blob/1ce8795973cb53ebce810e9bd03db41f8c98538f/chapter/cp4.tex#L18

**Comment by viokula** [comment]
![image](https://github.com/Ftine/SZU_Latex_Master_Template/assets/22325714/2c9cef83-e6e6-42d3-b638-f7d416d5874d) 这个有修改好吗？

**Comment by Ftine** [comment]
> ![image](https://private-user-images.githubusercontent.com/22325714/307674046-2c9cef83-e6e6-42d3-b638-f7d416d5874d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDcwNzIsIm5iZiI6MTcwODk0Njc3MiwicGF0aCI6Ii8yMjMyNTcxNC8zMDc2NzQwNDYtMmM5Y2VmODMtZTZlNi00MmQzLWI2MzgtZjdkNDE2ZDU4NzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDExMjYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZGRjYjllNGZlN2IxMDczOTgyNDI5MzI5NGQ2NDkyOGVmNDlmODE4NzZjNjhhZDA3YzZiNDVjZTgyYjZkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._dQbVfiSDDaZx60fpu66VDGRJy8yB_aQD0whQE3to-I) 这个有修改好吗？这个有修改好吗？

暂时没有 想过许多办法 但无法完成更改。

**Comment by Ftine** [comment]
> 使用`\upcite`
> 
> https://github.com/Ftine/SZU_Latex_Master_Template/blob/1ce8795973cb53ebce810e9bd03db41f8c98538f/chapter/cp4.tex#L18

感谢回复

**Comment by Hoantrbl** [comment]
> 使用`\upcite`
> 
> https://github.com/Ftine/SZU_Latex_Master_Template/blob/1ce8795973cb53ebce810e9bd03db41f8c98538f/chapter/cp4.tex#L18

连续引用知道怎么解决吗，模板要求[15,16]这类连续引用要写成[15-16] @Ftine

**Comment by Ftine** [comment]
> > 使用`\upcite`
> > https://github.com/Ftine/SZU_Latex_Master_Template/blob/1ce8795973cb53ebce810e9bd03db41f8c98538f/chapter/cp4.tex#L18
> 
> 连续引用知道怎么解决吗，模板要求[15,16]这类连续引用要写成[15-16] @Ftine

[12-19]这种格式bibTex会自动实现，两篇文献不会使用[xx-xx]符号。
