### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by ZFNSQM** [Ftine/SZU_Latex_Master_Template#11]
1.会议的引用文献以"."结束，但学校给的模板是以"//"结束的。
2.会议的volume是"Vol xx"表示，但期刊的volume是"(xx)"表示，不统一。
请问如果想修改引用文献的格式要怎么修改，修改根目录下的gbt7714-2005.bst没有起作用。

**Comment by ZFNSQM** [comment]
已解决，修改根目录下的gbt7714-2005.bst，修改完后要把编译缓存(master_pang.xxx)的文件都删掉，重新编译才起作用。
1. FUNCTION {inbook.impl}中，把cap.period write$换成cap.double.slash write$
2. 首先在FUNCTION {get.full.booktitle}中，把volume非空的情况改为与空一致。最后在FUNCTION {inbook.impl}中合适的位置添加false output.volume和false output.number。

把gbt7714-2005.txt后缀改为.bst
[gbt7714-2005.txt](https://github.com/Ftine/SZU_Latex_Master_Template/files/14716892/gbt7714-2005.txt)

**Comment by Ftine** [comment]
具体多少行 可以分享嘛？ 我不清楚 你这个我应该怎么更新

> 已解决，修改根目录下的gbt7714-2005.bst，修改完后要把编译缓存(master_pang.xxx)的文件都删掉，重新编译才起作用。
> 
> 1. FUNCTION {inbook.impl}中，把cap.period write$换成cap.double.slash write$
> 2. 首先在FUNCTION {get.full.booktitle}中，把volume非空的情况改为与空一致。最后在FUNCTION {inbook.impl}中合适的位置添加false output.volume和false output.number。
> 
> 把gbt7714-2005.txt后缀改为.bst [gbt7714-2005.txt](https://github.com/Ftine/SZU_Latex_Master_Template/files/14716892/gbt7714-2005.txt)

**Comment by ZFNSQM** [comment]
就是修改项目根目录下的gbt7714-2005.bst。
1.第1750行的cap.double.slash write$ 注释打开。第1751行注释掉。这个是把会议改为"//"结束。
2. 在第1762行下面添加 false output.volume, false output.number。这个是把volume和number的格式与article格式统一。
![1](https://github.com/Ftine/SZU_Latex_Master_Template/assets/164338937/2e492816-e0c6-43eb-997d-d117ee9c2100)

3.FUNCTION {get.full.booktitle} ，把volume相关的注释掉。反正就是显示booktitle，booktitle后面不用跟volume了。
![2](https://github.com/Ftine/SZU_Latex_Master_Template/assets/164338937/309bb6ee-cb8b-490c-8468-12c9a5ba0a6a)

**Comment by modest-Hamilton** [comment]
个人猜测出现这个问题的原因是使用的是gbt714-2005的文件，学校论文格式规范要求已经更新为国标2015（GB/T7714-2015）了。这里提供一个其他方案供参考，但不确定能否完全解决以上两个问题。（这个方案原本是用来解决：当正文中出现两篇连续的文献引用时，引用格式为[255,256]，而非[255-256]的问题）
![微信图片_20240323150703](https://github.com/Ftine/SZU_Latex_Master_Template/assets/131780278/25aab342-46c0-40b8-91ca-5f3ca568e3b8)

以下是具体操作：
1. 首先需要引入两个额外的文件
[gbt77142015.zip](https://github.com/Ftine/SZU_Latex_Master_Template/files/14730567/gbt77142015.zip)
2. 在论文主Tex文件中加入以下片段
```
% 参考文献包
\usepackage{gbt7714}
...
\begin{document}
...
%修改参考文献行距，感觉1.5pt与模板行距较为一致
\setlength{\bibsep}{1.5pt} 
\begin{spacing}{1.8}
    \bibliographystyle{gbt7714-numerical}
	\bibliography{references}
\end{spacing}
...
\end{document}
```



参考了[gbt7714-bibtex-style](https://github.com/zepinglee/gbt7714-bibtex-style)

**Comment by ZFNSQM** [comment]
> 个人猜测出现这个问题的原因是使用的是gbt714-2005的文件，学校论文格式规范要求已经更新为国标2015（GB/T7714-2015）了。这里提供一个其他方案供参考，但不确定能否完全解决以上两个问题。（这个方案原本是用来解决：当正文中出现两篇连续的文献引用时，引用格式为[255,256]，而非[255-256]的问题） ![微信图片_20240323150703](https://private-user-images.githubusercontent.com/131780278/316224449-25aab342-46c0-40b8-91ca-5f3ca568e3b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzgzMTcsIm5iZiI6MTcxMTE3ODAxNywicGF0aCI6Ii8xMzE3ODAyNzgvMzE2MjI0NDQ5LTI1YWFiMzQyLTQ2YzAtNDBiOC05MWNhLTVmM2NhNTY4ZTNiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwNzEzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTNjYWFhNGU1YTQwM2M4ZWExM2U0NjY5NTQxY2ZlNzIwMmM5MTQ1NWE0YTRhOTljYzRkNDQxMTM3ZTJkZmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uPdVW3yshw2qkWExUpvBsYoNVpKqZzuwsVzF2nm_opQ)
> 
> 以下是具体操作：
> 
> 1. 首先需要引入两个额外的文件
>    [gbt77142015.zip](https://github.com/Ftine/SZU_Latex_Master_Template/files/14730567/gbt77142015.zip)
> 2. 在论文主Tex文件中加入以下片段
> 
> ```
> % 参考文献包
> \usepackage{gbt7714}
> ...
> \begin{document}
> ...
> %修改参考文献行距，感觉1.5pt与模板行距较为一致
> \setlength{\bibsep}{1.5pt} 
> \begin{spacing}{1.8}
>     \bibliographystyle{gbt7714-numerical}
> 	\bibliography{references}
> \end{spacing}
> ...
> \end{document}
> ```
> 
> 参考了[gbt7714-bibtex-style](https://github.com/zepinglee/gbt7714-bibtex-style)

我试了一下，期刊和会议的卷Vol格式还是会不统一

**Comment by viokula** [comment]
还有个问题，就是中文文章"等人"用的是"et al"，这不符合标准

**Comment by ZFNSQM** [comment]
可以参考这个[https://blog.csdn.net/weixin_44911552/article/details/124976926](url)

> 还有个问题，就是中文文章"等人"用的是"et al"，这不符合标准

**Comment by AplusMon** [comment]
其实还有个问题，就是参考文献的序号并没有靠左对齐。在该模板文件中，参考文献序号[1-9]均对应十位数字的个位数，即：例如[9]对应[10]中的0，而在学校发的模板中，应该是[9]对应[10]中的[1]。

**Comment by modest-Hamilton** [comment]
> 其实还有个问题，就是参考文献的序号并没有靠左对齐。在该模板文件中，参考文献序号[1-9]均对应十位数字的个位数，即：例如[9]对应[10]中的0，而在学校发的模板中，应该是[9]对应[10]中的[1]。

可以考虑参考我的方法，中文文献的“等”与序号对齐这两个问题我这边没有出现

**Comment by Ftine** [comment]
> > 其实还有个问题，就是参考文献的序号并没有靠左对齐。在该模板文件中，参考文献序号[1-9]均对应十位数字的个位数，即：例如[9]对应[10]中的0，而在学校发的模板中，应该是[9]对应[10]中的[1]。
> 
> 可以考虑参考我的方法，中文文献的“等”与序号对齐这两个问题我这边没有出现

尽可以解决这个问题，我尝试以后，出现. arXiv preprint arXiv:2202.03958,文章引用错误，无法显示arXiv preprint。

**Comment by Donkdot** [comment]
arXIv的问题应该需要去arxiv官网导出@misc格式的bibtex，就可以了。但是会议和期刊的Vol表现形式不同应该如何解决呢？

**Comment by Ftine** [comment]
> arXIv的问题应该需要去arxiv官网导出@misc格式的bibtex，就可以了。但是会议和期刊的Vol表现形式不同应该如何解决呢？

我没管它了，直接交

**Comment by viokula** [comment]
参考文献格式有大问题
<img width="632" alt="截屏2024-03-29 15 34 09" src="https://github.com/Ftine/SZU_Latex_Master_Template/assets/22325714/3b9913af-0d77-4633-ba5e-5a706758260b">

**Comment by viokula** [comment]
原格式都没有缩写

**Comment by viokula** [comment]
原格式没有大写

**Comment by ZFNSQM** [comment]
在.bst文件里的FUNCTION {format.names}函数里修改一下。
![微信截图_20240329165336](https://github.com/Ftine/SZU_Latex_Master_Template/assets/164338937/f4ce4644-8542-43d2-a5db-0ca1a1ffe7ca)


> 原格式没有大写

**Comment by viokula** [comment]
好了，谢谢
