### ISSUE TITLE
摘要与标题格式

### ISSUE THREAD

**Issue by modest-Hamilton** [Ftine/SZU_Latex_Master_Template#12]
### 摘要格式
摘要部分模板要求如下

> 关键词： 摘要下方空一行之后居左写“关键词” 三个字， 采用黑体小四号加粗； 冒号后接关键词内容， 采用宋体小四号， 行距为 23 磅； 每个关键词之间用逗号间隔。

因此，可能需要将szu2024.cls的关键词部分更改为空一行，而且个人发现如果把关键词直接写在cls文件中，可以避免“关键词：”与具体的关键词之间产生较大的空格，英文也是。
```
%中文关键词
\newenvironment{keywordCN}{
	\vspace{1\baselineskip}	%空一行
        \fancyhead[C]{\songti\zihao{5}{\titleCN}}
	\fancyfoot[C]{\songti\zihao{5}{\thepage}}
	\songti\zihao{-4}
        \thispagestyle{fancy}
	\noindent{{\heiti\zihao{-4}\textbf{关键词：}{\songti\zihao{-4}关键词1，关键词2，关键词3}}}
}
{\newpage}

%英文关键词
\newenvironment{keywordEN}{
	\fancyhead[C]{\songti\zihao{5}{\titleEN}}
	\fancyfoot[C]{\songti\zihao{5}{\thepage}}
	\vspace{1\baselineskip}	%空一行
	\songti\zihao{-4}
    \thispagestyle{fancy}
	\noindent{\textbf{Key words: }{keyword1, keyword2, keyword3}}
 }
```
### 标题格式
标题格式要求如下
> 节标题： 大纲级别 2 级， 采用小三号字加粗， 中文和数字用黑体， 英文用 Arial 体， 居左书写， 单倍行距， 段前 24 磅， 段后 6磅， 节序号与名称之间空 1 个汉字符。

目前只能做到将数字改为黑体，英文还不知道如何改成Arial，而且不确定这种方式修改会不会出问题，我也不太懂latex。提供一个参考的cls文件。
此外还需要导入黑体的ttf文件，在windows电脑中`C:\Windows\Fonts`路径下一般都有。
[szuMA.txt](https://github.com/Ftine/SZU_Latex_Master_Template/files/14773459/szuMA.txt)

**Comment by Ftine** [comment]
有心了，辛苦
