### ISSUE TITLE
页眉

### ISSUE THREAD

**Issue by viokula** [Ftine/SZU_Latex_Master_Template#13]
页眉中英文全部大写了，这怎么处理？

**Comment by Ftine** [comment]
建议你给出示例，只有文字无法直观理解你的问题

**Comment by viokula** [comment]
<img width="302" alt="截屏2024-03-28 12 10 39" src="https://github.com/Ftine/SZU_Latex_Master_Template/assets/22325714/184d6507-3a35-4781-a2bf-cad6cd7bf13f">如图，目前我尝试在每个章节的tex文件中重新设置页眉的格式

**Comment by SuMoshen** [comment]
页眉页脚颜色是灰色的，大家记得改下颜色

**Comment by SuMoshen** [comment]
![image](https://github.com/Ftine/SZU_Latex_Master_Template/assets/43572727/3951c5e6-b5eb-4143-bb59-ee96ba45030b)
![image](https://github.com/Ftine/SZU_Latex_Master_Template/assets/43572727/d3cc8917-4f7f-461b-9545-92e6948b8f27)
还要引下包：\usepackage{xcolor}

**Comment by Ftine** [comment]
> 页眉页脚颜色是灰色的，大家记得改下颜色

你是好心的但是请你不要逗我，word中是灰色是word编辑器的页眉页脚显示，但是pdf不是啊，那只是word显示的问题。你自己可以生成pdf查证一下先。

**Comment by SuMoshen** [comment]
> > 页眉页脚颜色是灰色的，大家记得改下颜色
> 
> 你是好心的但是请你不要逗我，word中是灰色是word编辑器的页眉页脚显示，但是pdf不是啊，那只是word显示的问题。你自己可以生成pdf查证一下先。

抱歉抱歉~确实不用修改

**Comment by Ftine** [comment]
> <img alt="截屏2024-03-28 12 10 39" width="302" src="https://private-user-images.githubusercontent.com/22325714/317587989-184d6507-3a35-4781-a2bf-cad6cd7bf13f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjU5NjEsIm5iZiI6MTcxMTg2NTY2MSwicGF0aCI6Ii8yMjMyNTcxNC8zMTc1ODc5ODktMTg0ZDY1MDctM2EzNS00NzgxLWEyYmYtY2FkNmNkN2JmMTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA2MTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMDRlYTc0Y2RjYmFkNDk2NjQ3MDliYjYwMTkxZWY3ZDUwMTA4MDQ1NGViOTYxY2QwNzc4NmQ2Yjc5Mzk3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aI25g-5ZjPuP7UWBV1YDSoP8Zdk-7pPj--d3aXR5TmI">如图，目前我尝试在每个章节的tex文件中重新设置页眉的格式

更改如下：
 % 全局页眉 设置为章节标题
        \fancyhead[C]{\songti\zihao{5}\nouppercase\leftmark}
