### ISSUE TITLE
添加最后两页到目录

### ISSUE THREAD

**Issue by Donkdot** [Ftine/SZU_Latex_Master_Template#15]
老哥 学校新发的模板 最后加的评审结果 需要在目录中显示 这个要怎么搞呢？

**Comment by jackyrwj** [comment]
### 1）在master_pang.tex文件的末尾，\end{document}之前，添加以下内容：

% 在目录中添加最后两页
\addtocontents{toc}{\protect\noindent 附:指导教师对研究生学位论文的学术评语\par}
\addtocontents{toc}{答辩委员会决议书}

% 实际插入最后两页
\includepdf[pages={1}]{chapter/xspl.pdf}
\includepdf[pages={1,2}]{chapter/jys.pdf}

### 2）在文件结构最外层，chapter文件夹中，分别添加xspl.pdf和jys.pdf两个文件，分别为《指导教师对研究生学位论文的学术评语》和《答辩委员会决议书》。

**Comment by Ftine** [comment]
在 \end{document} 之前插入。

% 在目录中添加一段文本
\addtocontents{toc}{\noindent 附：指导教师对研究生学位论文的学术评语\par}
\addtocontents{toc}{答辩委员会决议书\par}
