### ISSUE TITLE
表格竖分割线无法穿透

### ISSUE THREAD

**Issue by Hoantrbl** [Ftine/SZU_Latex_Master_Template#16]
<img width="399" alt="image" src="https://github.com/Ftine/SZU_Latex_Master_Template/assets/48271804/37535b8f-c4d2-4e2c-8f5a-b03679f1dde7">
<img width="397" alt="image" src="https://github.com/Ftine/SZU_Latex_Master_Template/assets/48271804/ee2fdf35-8826-45b2-8532-be6dbbe6bd41">

用的包有\usepackage{threeparttable} 然后分割线用的都是midrule，toprule，不知道为啥失效了

**Comment by Hoantrbl** [comment]
求解决！

**Comment by Ftine** [comment]
聪明的研究生啊，我不是神，你可以chatGPT解决等，这是你写表格的问题，不是我的模板问题
