### ISSUE TITLE
四级标题好像无法用\paragraph

### ISSUE THREAD

**Issue by LusGroup** [Ftine/SZU_Latex_Master_Template#2]
四级标题好像无法用\paragraph，请问应该如何解决

**Comment by LusGroup** [comment]
有个方法，就是小笨，需要手动写一下第四级标题的章节号，比如这样
\paragraph{3.3.2.3 不同用户的影响}
\mbox{}\\%强制换行

**Comment by Ftine** [comment]
> 四级标题好像无法用\paragraph，请问应该如何解决

我不是很建议使用四级标题，格式上不美观 区分度不大。
如果你必须要四级标题，以下是如何更改的内容：

在 **szu2024.cls** 文件末尾找到section设置：% section title设置
`
\CTEXsetup[name={第,章},number={\chinese{section}}]{section}
\CTEXsetup[format+={\heiti\bfseries\zihao{3}}]{section}


\CTEXsetup[name={,},number={\thesubsection}]{subsection}
\CTEXsetup[format+={\heiti\bfseries\zihao{-3}}]{subsection}

\CTEXsetup[name={,},number={\thesubsubsection}]{subsubsection}
\CTEXsetup[format+=
{\songti\bfseries\zihao{4}}]{subsubsection}
`

在其末尾 在添加四级标题设置 

\CTEXsetup[name={,},number={\thesubsubsubsection}]{subsubsubsection}
\CTEXsetup[format+=
{\songti\bfseries\zihao{-4}}]{subsubsection}

**Comment by Ftine** [comment]
> 有个方法，就是小笨，需要手动写一下第四级标题的章节号，比如这样 \paragraph{3.3.2.3 不同用户的影响} \mbox{}\%强制换行

该模板标题全部采用section设置的 四级标题是 subsubsubsection

**Comment by Donkdot** [comment]
你好 按照您说的方法添加代码后 overleaf报错 The key 'ctex/subsubsubsection/name' is unknown and is being
