### ISSUE TITLE
模板公式编号采用形如3-1的格式

### ISSUE THREAD

**Issue by modest-Hamilton** [Ftine/SZU_Latex_Master_Template#3]
https://github.com/Ftine/SZU_Latex_Master_Template/blob/0a60e93f74610de7a21f07f783e11cc4d603af62/master_pang.tex#L96

`\renewcommand\theequation{{\thesection}-{\arabic{equation}}}`

**Comment by Ftine** [comment]
感谢 感谢 ！！！ 小细节 没有注意到。

**Comment by Ftine** [comment]
> https://github.com/Ftine/SZU_Latex_Master_Template/blob/0a60e93f74610de7a21f07f783e11cc4d603af62/master_pang.tex#L96
> 
> `\renewcommand\theequation{{\thesection}-{\arabic{equation}}}`


感谢提醒。 小细节 没有注意到。
