### ISSUE TITLE
中文硕士论文无法引用，求解决

### ISSUE THREAD

**Issue by viokula** [Ftine/SZU_Latex_Master_Template#4]

**Comment by Ftine** [comment]
中文引用，请手动更改为bibTex格式。

**Comment by viokula** [comment]
改了，知网有相应的bibtex引用格式，但是引用不上

**Comment by Ftine** [comment]
> 改了，知网有相应的bibtex引用格式，但是引用不上

这是我的引用格式。
@article{yanghaiming2019,
  title={时间序列预测方法综述},
  author={杨海民 and 潘志松 and 白玮},
  journal={计算机科学},
  volume={46},
  number={1},
  pages={21--28},
  year={2019}
}

你可以看看是否可以引用上

**Comment by viokula** [comment]
可能我没说清楚，是中文的硕士论文，不是中文会议或期刊文章。中文文章是可以的，但就是硕士论文不行

**Comment by disturb-yy** [comment]
@phdthesis{朱刚1996新型流体有限元法及叶轮机械正反混合问题,
  title={新型流体有限元法及叶轮机械正反混合问题},
  author={朱刚},
  school={清华大学},
  year={1996},
}
[1] 朱刚. 新型流体有限元法及叶轮机械正反混合问题 [D]. [S.l.] : 清华大学, 1996.
是像上面出现[S.l.]的问题吗？如果是的话可以自己添加一个address选项，如address={北京}

**Comment by Ftine** [comment]
@disturb-yy 感谢你的回复
@viokula  我确实理解错了，不好意思。
中文的硕士引用 和 博士引用基本一致。

博士格式：
@phdthesis{zhu1996,
title={新型流体有限元法及叶轮机械正反混合问题},
author={朱刚},
school={清华大学},
address={北京},
year={1996},
}

硕士：
@masterthesis{zhu1996,
title={新型流体有限元法及叶轮机械正反混合问题},
author={朱刚},
school={清华大学},
address={北京},
year={1996},
}
