### ISSUE TITLE
中文摘要有两页时，第一页的页眉会消失，求解决

### ISSUE THREAD

**Issue by disturb-yy** [Ftine/SZU_Latex_Master_Template#5]
![微信截图_20240305233453](https://github.com/Ftine/SZU_Latex_Master_Template/assets/38591234/bbc18215-8f7c-438a-9a68-961e809bfb96)

**Comment by Ftine** [comment]
ok

**Comment by Ftine** [comment]
已修复

**Comment by LusGroup** [comment]
请问具体怎么修复的呀，需要加什么语句呢

**Comment by LusGroup** [comment]
> 已修复

你好，替换了clc还是不行呢
