### ISSUE TITLE
表格的一些问题

### ISSUE THREAD

**Issue by PnZheng** [Ftine/SZU_Latex_Master_Template#7]
老哥，这个表格当加上竖线后会出现这种情况，要么最上面那行没有竖线，请问能搞一下吗
![微信图片_20240311152926](https://github.com/Ftine/SZU_Latex_Master_Template/assets/40221248/7a57b437-ec4e-4cfe-8fdb-3b3d4af24b6c)

**Comment by Ftine** [comment]
这个我不知道，你可以尝试自己百度谷歌解决。其次建议按学校要求使用三线表，不要加竖线。

**Comment by PnZheng** [comment]
好的，多谢
