### ISSUE TITLE
目录没有页码

### ISSUE THREAD

**Issue by miRemid** [Ftine/SZU_Latex_Master_Template#9]
现在生成的目录没有从摘要往后顺延的页码，学校Word给的模板里面是有的

请问要怎么设置？

**Comment by Hoantrbl** [comment]
同问

<img width="356" alt="image" src="https://github.com/Ftine/SZU_Latex_Master_Template/assets/48271804/300d4d6c-07d1-491a-a402-cf94e97e9d6b">

**Comment by modest-Hamilton** [comment]
https://github.com/Ftine/SZU_Latex_Master_Template/blob/c78caf142ac9867fedf01c588fd089cf100118af/szu2024.cls#L89
将此行目录设置改为如下形式
```
\pagestyle{plain}
```
